### ISSUE TITLE
Question about simpleasmjit.cpp?

### ISSUE THREAD

**Issue by zzl0** [eliben/code-for-blog#13]
Firstly, thanks for your awesome blog articles, I really enjoyed reading them.

Recently I tried to run your `bfjit` code. I found `simpleasmjit.cpp` can compile successfully on my **Mac**, but when I ran it, I got a `segmentation fault`. It was caused by calling the [asmjit emitted code](https://github.com/eliben/code-for-blog/blob/master/2017/bfjit/simpleasmjit.cpp#L160). 

I am not familiar with assembly code, I have read the code (simpleasmjit), but I couldn't find any system sepcific feature in that file. I am not sure it's because of `simpleasmjit` is using linux specific feature or there is a "bug" in `asmjit`? Could you give me some advices to dive into it?

**Comment by eliben** [comment]
Nope, I did not try it on a Mac. I'll gladly accept PRs that fix Mac support though

**Comment by zzl0** [comment]
Thanks, I will try to make it support Mac.
