### ISSUE TITLE
Should the pipe overhead not be subtracted from the context switch overhead?

### ISSUE THREAD

**Issue by ankit-iitb** [eliben/code-for-blog#18]
Hi,

The [post](https://eli.thegreenplace.net/2018/measuring-context-switching-and-memory-overheads-for-linux-threads/) was a nice read about the thread context switch overheads.

However, I have one question. Even though you measure the pipe overhead but don't subtract that from the overall context switch overhead to get just the switching cost. 

Shouldn't it be `(elapsed / (float)nswitches) - overhead` [here](https://github.com/eliben/code-for-blog/blob/a55d86d6c3260d1c9e2556edb536c51002316a84/2018/threadoverhead/thread-switch-pipe.c#L137), where the value of  `overhead` is `double overhead = measure_self_pipe(NUM_ITERATIONS);`

`lmbench` also subtracts the overhead from the overall context switch cost before printing [Link](https://github.com/intel/lmbench/blob/b5dfe4f17a4d72d5d3df4b80bcae0e87bbea2adc/src/lat_ctx.c#L119).

It will be really helpful if you could explain, why are you not subtracting the overhead from the overall context switch cost.

**Comment by eliben** [comment]
The code doesn't subtract it but I did subtract it for the blog post graphs.
