### ISSUE TITLE
XML file for XML streaming project?

### ISSUE THREAD

**Issue by carlmjohnson** [eliben/code-for-blog#19]
I want to test the performance of adding `bufio.NewReader` to the Go standard library XML streamer, but I don't have the XML you used. Can you post it somewhere?

**Comment by eliben** [comment]
The post has a link to `xmlgen` which I used, with `-f 2` to generate a ~230 MiB file

**Comment by carlmjohnson** [comment]
Okay. I did some tests with a different file and it didn't make a difference to use bufio.Reader.
