### ISSUE TITLE
Unable to import lexar

### ISSUE THREAD

**Issue by keshav1245** [eliben/code-for-blog#20]
I installed pygments yet unable to import lexar 
tried import pygments.lexar as lexar 
yet error was thrown out 

<pre>File &quot;unify.py&quot;, line 210, in &lt;module&gt;
    subst = unify(parse_term(s1), parse_term(s2), {})
  File &quot;unify.py&quot;, line 57, in parse_term
    parser = TermParser(s)
  File &quot;unify.py&quot;, line 75, in __init__
    self.lexer = lexer.Lexer(lexrules, skip_whitespace=True)
TypeError: __init__() takes 1 positional argument but 2 were given</pre>

Kindly help me out for running the code properly

**Comment by eliben** [comment]
Sorry, I don't understand what you're asking. What is `lexar`? What code are you trying to run? What has `pygments` to do with it?

**Comment by keshav1245** [comment]
oh I am sorry, actually I just navigated from your blog link to the 2018/unif/unify.py code and did not check the unif folder. In unify.py the first line says import lexar and I was unabale to do so... checked it now that you have another file called lexar.py and now its working...Really sorry, my bad.

Regards
