### ISSUE TITLE
Shouldn't size_t be std::size_t in tuple.h?

### ISSUE THREAD

**Issue by kurt-krueckeberg** [eliben/code-for-blog#21]
Hi,
Thanks for the code. Shouldn't **size_t** be **std::size_t**  throughout tuple.h. For example, shouldn'n
    template <size_t, class> struct elem_type_holder;
be
   template <std::size_t, class> struct elem_type_holder;

**Comment by eliben** [comment]
Sure, feel free to send a pull request

**Comment by eliben** [comment]
This seems to have been addressed in bfb89d2220b2b5fc2f482542cb38573955cbbdc2
