### ISSUE TITLE
Py-RD-Parser not working well for booleans

### ISSUE THREAD

**Issue by Obround** [eliben/code-for-blog#24]
I tried your [recursive descent parser code](https://github.com/eliben/code-for-blog/blob/master/2009/py_rd_parser_example/rd_parser_ebnf.py) and it worked, but when I tried:
```python
print(p.calc("1>1!=2"))
```
I got this error:
```
Traceback (most recent call last):
  File "main.py", line 452, in <module>
    print(p.calc("1>1!=2"))
  File "main.py", line 126, in calc
    self.cur_token.val, self.cur_token.pos))
  File "main.py", line 169, in _error
    raise ParseError(msg)
__main__.ParseError: Unexpected token != (at #3)
```
Why does this happen?

**Comment by Obround** [comment]
I believe `!=` and `==` should have lower precedence than `<`, `>`, etc.

**Comment by eliben** [comment]
This is just an example, to serve as the basis for a real implementation. Feel free to extend it as you wish.
