### ISSUE TITLE
rust-test-macros: Third attempt .... use `rstest`

### ISSUE THREAD

**Issue by la10736** [eliben/code-for-blog#29]
Just for joke... but https://crates.io/crates/rstest is exactly designed for this king of jobs :)

p.s. Disclaimer ... I' the `rstest`'s maintainer :)

**Comment by eliben** [comment]
Thanks for your note.

I'm well aware that there are a number of crates that help solve this issue, but my goal with the post was to see to implement it myself and explore macros for tests in the process.

**Comment by la10736** [comment]
I see but I guess that was fun :)
