### ISSUE TITLE
Wrong error check on the return value?

### ISSUE THREAD

**Issue by juliengrimault** [eliben/code-for-blog#6]
I think there is an error In the following line of code when testing for error in the the returned value

https://github.com/eliben/code-for-blog/blob/200be4cc380fd62dd01ef50c3d19d4611af54a60/2011/debuggers_part2_code/debuglib.c#L133

I think it should be
```
if (ptrace(PTRACE_SINGLESTEP, pid, 0, 0) < 0) { 
```

**Comment by eliben** [comment]
Thanks, fixed!
