### ISSUE TITLE
Number of thread switches

### ISSUE THREAD

**Issue by hxer7963** [eliben/code-for-blog#60]
hello, eliben. I read the excellent blog() about how to benchmark the Linux OS thread switch, and carefully read and run the relevant code under `threadoverhead` dir tree. 

I have a question about **why the iteration num don't need to multiple 2 in thread-pipe-msgpersec.c and channel-msgpersec.go**, which I think each thread/goroutine is scheduled `NUM_ITERATIONS/niters` times, so when calculating each scheduling delay, the total number of scheduled times should be the **sum** of the number of times two threads have been scheduled?

**Comment by eliben** [comment]
I think the blog post explains in, beginning with "Running the benchmark on the same machine"...
