### ISSUE TITLE
possible to get longer rss feed?

### ISSUE THREAD

**Issue by phanirithvij** [eliben/code-for-blog#66]
Your rss feeds only go back 10 entries, possible to get a new feed for all of them which go way back?
i.e. new feeds (or modify old feeds, not sure how this effects the current subscribers).
eg. https://eli.thegreenplace.net/feeds/go.atom.xml and now https://eli.thegreenplace.net/feeds/go.full.atom.xml
https://eli.thegreenplace.net/feeds/all.atom.xml and https://eli.thegreenplace.net/feeds/all.full.atom.xml

**Comment by eliben** [comment]
Why would you need it going farther back?

The blog has well over a thousand posts - full/longer feeds will be huge, which is additional serving overhead.

**Comment by phanirithvij** [comment]
Okay, I didn't see that there were thousands.
