### ISSUE TITLE
Server stuck @ start if run with SBATCH / srun

### ISSUE THREAD

**Issue by Sonyoyo** [eliben/code-for-blog#68]
Hello,

I am trying to run your code for distributed python. 
When I run it "manually" everything goes fine (the server starts and I can than connect the clients to it).
However the server never starts when I try to launch the whole thing via SBATCH / `srun`. I can see the python script starting, it reach the `manager.start()` line (a `print` added to the previous line is printed) but never goes to the following (I have no error message, but the `print` of the following line is never displayed and the clients cannot connect to the server).

https://github.com/eliben/code-for-blog/blob/27c13c32832792789822675bb5c08a7add655045/2012/parallel_python_multiprocessing/distributed_factor.py#L80

I have also tried to log into the nodes and then run the script "manually" from there: in that case everything is OK, so it is really linked to how `srun` launches the python script... do you have any idea of what can go wrong here?

Thanks in advance.

**Comment by eliben** [comment]
I'm not really familiar with SBATCH / srun, so I'm not sure I can help here. This is also fairly old code that I haven't been working with in quite a while

**Comment by Sonyoyo** [comment]
Thanks for replying. 
I run some more tests and even if I still have some weird and unexpected results, I found out that I can launch the server in the sbatch script without the `srun` command, which make the server to properly work. The clients can be launched by `srun` so that they are distributed on the other nodes.
