### ISSUE TITLE
Question about the multithreading blog.

### ISSUE THREAD

**Issue by justinjk007** [eliben/code-for-blog#7]
```cpp
int main(int argc, const char** argv) {
  unsigned num_cpus = std::thread::hardware_concurrency();
  std::cout << "Launching " << num_cpus << " threads\n";

  // A mutex ensures orderly access to std::cout from multiple threads.
  std::mutex iomutex;
  std::vector<std::thread> threads(num_cpus);
  for (unsigned i = 0; i < num_cpus; ++i) {
    threads[i] = std::thread([&iomutex, i] {
      {
        // Use a lexical scope and lock_guard to safely lock the mutex only for
        // the duration of std::cout usage.
        std::lock_guard<std::mutex> iolock(iomutex);
        std::cout << "Thread #" << i << " is running\n";
      }

      // Simulate important work done by the tread by sleeping for a bit...
      std::this_thread::sleep_for(std::chrono::milliseconds(200));

    });
  }

  for (auto& t : threads) {
    t.join();
  }
  return 0;
}
```

This is from your [blog](https://eli.thegreenplace.net/2016/c11-threads-affinity-and-hyperthreading/). I was wondering the way you create the threads based on the number of CPU cores, isn't that 1 more ? 

The main function is already a thread right ?

Also ` threads[i] = std::thread([&iomutex, i]` what is this syntax ? I couldn't find an explanation about it.

**Comment by eliben** [comment]
In this case the main thread is idle so it doesn't matter.

That syntax is C++ lambdas.

**Comment by justinjk007** [comment]
Ohh... thanks. How do you know the thread is idle? Because you are not
doing any work there?

**Comment by eliben** [comment]
The main thread is not doing any work besides waiting for the child threads to finish in the last loop which calls `join`.

**Comment by justinjk007** [comment]
Ahh...ok. Thanks.
