### ISSUE TITLE
 Notes on running Go in the browser with WebAssembly

### ISSUE THREAD

**Issue by 3052** [eliben/code-for-blog#70]
https://eli.thegreenplace.net/2024/notes-on-running-go-in-the-browser-with-webassembly/

you give this:

~~~js
const go = new Go();
~~~

but you dont really explain where `Go()` comes from, that I can tell. this is an important detail, as I believe its probably some glue code

**Comment by eliben** [comment]
It comes from `wasm_exec.js` that's mentioned a bit further down. I will mention it in a comment, but in general this post is not intended to be the first tutorial on the topic.
