### ISSUE TITLE
2011/socket_client_thread_sample /socketclientthread.py Why receive command supplies data?

### ISSUE THREAD

**Issue by gitgithan** [eliben/code-for-blog#72]
https://github.com/eliben/code-for-blog/blob/main/2011/socket_client_thread_sample/socketclientthread.py#L141

```
if __name__ == "__main__":
    sct = SocketClientThread()
    sct.start()
    sct.cmd_q.put(ClientCommand(ClientCommand.CONNECT, ('localhost', 50007)))
    reply = sct.reply_q.get(True)
    print(reply.type, reply.data)
    sct.cmd_q.put(ClientCommand(ClientCommand.SEND, "hellothere"))
    reply = sct.reply_q.get(True)
    print(reply.type, reply.data)
    sct.cmd_q.put(ClientCommand(ClientCommand.RECEIVE, "hellothere"))
    reply = sct.reply_q.get(True)
    print(reply.type, reply.data)
    sct.cmd_q.put(ClientCommand(ClientCommand.CLOSE))
    reply = sct.reply_q.get(True)
    print(reply.type, reply.data)
    pass
```

`sct.cmd_q.put(ClientCommand(ClientCommand.RECEIVE, "hellothere"))`
I was expecting it to be `sct.cmd_q.put(ClientCommand(ClientCommand.RECEIVE))` which gives `ClientCommand` a default None for its `self.data`. 

`_handle_RECEIVE` and `_handle_CLOSE` never used `cmd.data`, only `_handle_CONNECT` and `_handle_SEND` used it, another piece of evidence receive needs no data in the ClientCommand object.

https://github.com/eliben/code-for-blog/blob/main/2011/socket_client_thread_sample/sampleguiclient.py#L97-L101
This section uses functions from above `from socketclientthread import SocketClientThread, ClientCommand, ClientReply`  and follows the expected usage pattern defined by the 4 handlers
```
    def on_doit(self):
        self.client.cmd_q.put(ClientCommand(ClientCommand.CONNECT, SERVER_ADDR))
        self.client.cmd_q.put(ClientCommand(ClientCommand.SEND, 'hello'))
        self.client.cmd_q.put(ClientCommand(ClientCommand.RECEIVE))
        self.client.cmd_q.put(ClientCommand(ClientCommand.CLOSE))
 ```

**Comment by eliben** [comment]
There's no special reason for this; the code in the `if __name__ == "__main__"` block is generally just for local testing while developing.
